/**
 * GPX (GPS Exchange Format) export utilities
 * Converts route data to GPX format for GPS devices
 */

/**
 * Generate GPX XML string from route data
 * @param {Object} route - Route object with waypoints
 * @returns {string} GPX XML string
 */
export function generateGPX(route) {
  const { route_name, waypoints, distance, elevation_gain, created_at } = route

  // GPX header
  let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="RunRoutes App" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapeXml(route_name)}</name>
    <desc>Route generated by RunRoutes - Distance: ${distance}km${elevation_gain ? `, Elevation: ${elevation_gain}m` : ''}</desc>
    <time>${new Date(created_at).toISOString()}</time>
  </metadata>
  <trk>
    <name>${escapeXml(route_name)}</name>
    <type>running</type>
    <trkseg>`

  // Add waypoints
  waypoints.forEach((point, index) => {
    gpx += `
      <trkpt lat="${point.lat}" lon="${point.lng}">
        ${point.elevation ? `<ele>${point.elevation}</ele>` : ''}
        <name>Point ${index + 1}</name>
      </trkpt>`
  })

  // GPX footer
  gpx += `
    </trkseg>
  </trk>
</gpx>`

  return gpx
}

/**
 * Download GPX file
 * @param {Object} route - Route object
 * @param {string} filename - Optional filename (defaults to route name)
 */
export function downloadGPX(route, filename = null) {
  const gpxContent = generateGPX(route)
  const blob = new Blob([gpxContent], { type: 'application/gpx+xml' })
  const url = URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = filename || `${sanitizeFilename(route.route_name)}.gpx`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Escape XML special characters
 * @param {string} str - String to escape
 * @returns {string} Escaped string
 */
function escapeXml(str) {
  if (!str) return ''
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/**
 * Sanitize filename for download
 * @param {string} filename - Original filename
 * @returns {string} Sanitized filename
 */
function sanitizeFilename(filename) {
  return filename
    .replace(/[^a-z0-9]/gi, '_')
    .replace(/_+/g, '_')
    .toLowerCase()
}

/**
 * Generate KML (Google Earth format) as alternative
 * @param {Object} route - Route object
 * @returns {string} KML XML string
 */
export function generateKML(route) {
  const { route_name, waypoints, distance, elevation_gain } = route

  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(route_name)}</name>
    <description>Distance: ${distance}km${elevation_gain ? `, Elevation: ${elevation_gain}m` : ''}</description>
    <Placemark>
      <name>${escapeXml(route_name)}</name>
      <LineString>
        <coordinates>`

  waypoints.forEach(point => {
    kml += `\n          ${point.lng},${point.lat}${point.elevation ? `,${point.elevation}` : ',0'}`
  })

  kml += `
        </coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>`

  return kml
}

/**
 * Download KML file
 * @param {Object} route - Route object
 * @param {string} filename - Optional filename
 */
export function downloadKML(route, filename = null) {
  const kmlContent = generateKML(route)
  const blob = new Blob([kmlContent], { type: 'application/vnd.google-earth.kml+xml' })
  const url = URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = filename || `${sanitizeFilename(route.route_name)}.kml`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

